// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK2SXL0xNmQZG6cra1jCRkoh8rv5-tp3w',
    appId: '1:775220992652:web:3d3c8c3658f44edd1bf9a9',
    messagingSenderId: '775220992652',
    projectId: 'note-app-af577',
    authDomain: 'note-app-af577.firebaseapp.com',
    storageBucket: 'note-app-af577.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-oXOnS9VFIp0uXKx9-f_qWwOckE6ol-8',
    appId: '1:775220992652:android:b0f3fd3472f39bcb1bf9a9',
    messagingSenderId: '775220992652',
    projectId: 'note-app-af577',
    storageBucket: 'note-app-af577.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo-J58GnlArbx1WKgls9KhZJyI3YDrzAk',
    appId: '1:775220992652:ios:c78e4cdbd01030d91bf9a9',
    messagingSenderId: '775220992652',
    projectId: 'note-app-af577',
    storageBucket: 'note-app-af577.appspot.com',
    iosBundleId: 'vn.qsoft.interview.note',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo-J58GnlArbx1WKgls9KhZJyI3YDrzAk',
    appId: '1:775220992652:ios:c78e4cdbd01030d91bf9a9',
    messagingSenderId: '775220992652',
    projectId: 'note-app-af577',
    storageBucket: 'note-app-af577.appspot.com',
    iosBundleId: 'vn.qsoft.interview.note',
  );
}
